#!/bin/bash

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"

setup_environment() {
  VENV_DIR="$DIR/venv"

  if [ ! -d "$VENV_DIR" ]; then
    echo "Creando entorno virtual..."
    python3 -m venv "$VENV_DIR" || return 1
    source "$VENV_DIR/bin/activate" || return 1
    echo "Instalando dependencias..."
    pip install --upgrade pip
    pip install -r "$DIR/requirements.txt" || return 1
  else
    source "$VENV_DIR/bin/activate" || return 1
  fi

  echo "Entorno listo."
}

case "$1" in
  -c|--client)
    cd "$BASE_DIR/client" || exit 1
    ng serve
    ;;

  -p|--preprocess)
    DIR="$BASE_DIR/preprocess_server"
    cd $DIR || exit 1
    setup_environment || exit 1
    uvicorn app.main:app --reload
    ;;

  -m|--ppml)
    DIR="$BASE_DIR/ppml_server"
    cd $DIR || exit 1
    setup_environment || exit 1
    uvicorn app.main:app --reload --port 8001
    ;;

  *)
    echo "Uso: $0 [-c|--client] [-p|--preprocess] [-m|--ppml]"
    ;;
esac